### ISSUE TITLE
osx上运行出错

### ISSUE THREAD

**Issue by Eveink** [houtianze/bypy#108]
bypy.py
Traceback (most recent call last):
  File "/usr/local/bin/bypy.py", line 5, in <module>
    pkg_resources.run_script('bypy==1.0.3', 'bypy.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1357, in run_script
    exec_(script_code, namespace, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 47, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/bypy-1.0.3-py2.7.egg/EGG-INFO/scripts/bypy.py", line 60, in <module>

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by houtianze** [comment]
按照这贴儿：https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python
应该在`~/.bash_profile`里加入这两行就OK了吧。
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
