### ISSUE TITLE
可以授权两个电脑设备么？

### ISSUE THREAD

**Issue by GoldCome** [houtianze/bypy#116]
本人尝试在一台电脑哦上授权使用没问题，但在另一个服务器上也想用这个百度帐号，授权成功了，但总是上传不了文件，错误代码如下：
```
Done
Comparing ...
Done
<D> 'why' is small and being non-slicing uploaded.
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/why
<D> Params: {u'path': u'/apps/bypy/why', u'ondup': u'overwrite', u'method': u'uplo
ad'}
<E> [23:49:49] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [23:49:49] Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail
ed (_ssl.c:581)
Traceback (most recent call last):
  File "/home/goldcome/bin/bypy", line 1027, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs
)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/
api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/
api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/
sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/
sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/
adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

<E> [23:49:49] Function: __upload_one_file_act
<E> [23:49:49] Website parameters: {u'path': u'/apps/bypy/why', u'ondup': u'overwr
ite', u'method': u'upload'}
<E> [23:49:49] Waiting 10 seconds before retrying...
```

**Comment by ibegyourpardon** [comment]
和多台设备应该没关系。我bypy安装在多台服务器上，一直良好，验证机制反正就 
是第一次使用的时候提示输入的验证字符串啊，那个通过了就一直没 问题。而且 
不同的设备用的肯定也是不同的验证字符串。

**Comment by houtianze** [comment]
SSL验证出了问题，刚才检查修复了这个bug。你试着下载下最新版，然后运行时加入`--disable-ssl-check`参数看看能不能解决问题？

**Comment by houtianze** [comment]
另外，升级到最新的`requests`应该可以解决这个问题：
(sudo) `pip install requests -U`

**Comment by GoldCome** [comment]
@ibegyourpardon  @houtianze  感谢答疑

@houtianze 
git pull升级了下，发现如下错误：
```
$ bypy list
  File "/home/goldcome/bin/bypy", line 124
    __version__ = 1.0.6
                      ^
SyntaxError: invalid syntax
```

看了下 这个<code>__version__ = 1.0.6 </code>这个变量应该要加上单引号，<code>__version__ = ’1.0.6‘</code>

本人系统环境：
  系统：Centos7 
  python版本：2.9

**Comment by GoldCome** [comment]
可以授权成功，也可以用list info命令查看，但还是无法上传下载  具体log如下，帮忙看下什么问题，我在另一台服务器上环境也类似，就没问题，就现在用这台出现这个问题。谢了！

```bash
[goldcome@CentOS temp]$ bypy upload hdd -d -v > test.log
[goldcome@CentOS temp]$ vim test.log
[goldcome@CentOS temp]$ cat test.log
Token file: '/home/goldcome/.bypy.json'
Hash Cache file: '/home/goldcome/.bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = None
Verbose level = 1
Debug = 1
----

Loading Hash Cache File '/home/goldcome/.bypy.pickle'...
Hash Cache File not found, no caching
<D> Token loaded:
<D> {u'access_token': u'21.c2c508475824f7636e694d219b00e1de.2592000.1425967200.2298967843-1572671', u'expires_in': 2592000, u'session_secret': u'76ad148583cacc07fdb94b36567d286e', u'scope': u'basic netdisk', u'session_key': u'9mnRJ9WNzNP6jTxsyS1lE72QffT9hMP+cw5iqJXNVCOnCykZ+FaOTZJR0OpACcH3sbrYVJV4VaUtdRvgNImYMo8eVjCoLSZtqA==', u'refresh_token': u'22.d446d501b1d255c9df38d61a0a79d9d4.315360000.1738735200.2298967843-1572671'}
<D> Uploading file 'hdd'
<D> __get_file_info(): rdir : /apps/bypy | rfile: hdd
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/hdd
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> HTTP Status Code: 200
<D> Request OK, processing action
<D> List json: {u'list': [{u'isdir': 1, u'ctime': 1423191933, u'fs_id': 265285115969819, u'mtime': 1423191933, u'path': u'/apps/bypy/app', u'md5': u'', u'size': 0}, {u'isdir': 1, u'ctime': 1423187559, u'fs_id': 834630456105269, u'mtime': 1423187559, u'path': u'/apps/bypy/gitlab', u'md5': u'', u'size': 0}, {u'isdir': 1, u'ctime': 1423173452, u'fs_id': 551999220372715, u'mtime': 1423173452, u'path': u'/apps/bypy/home', u'md5': u'', u'size': 0}, {u'isdir': 0, u'ctime': 1423332309, u'fs_id': 275768895260657, u'mtime': 1423332309, u'path': u'/apps/bypy/hello', u'md5': u'd41d8cd98f00b204e9800998ecf8427e', u'size': 0}], u'request_id': 605354929}
<D> remote path is '/apps/bypy/hdd'
<D> 'hdd' is small and being non-slicing uploaded.
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/hdd
<D> Params: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:02:42] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [14:02:42] Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Traceback (most recent call last):
  File "/home/goldcome/bin/bypy", line 1027, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

<E> [14:02:42] Function: __upload_one_file_act
<E> [14:02:42] Website parameters: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:02:42] Waiting 10 seconds before retrying...
<E> [14:02:52] Request Try #2 / 5
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/hdd
<D> Params: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:02:52] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [14:02:52] Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Traceback (most recent call last):
  File "/home/goldcome/bin/bypy", line 1027, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

<E> [14:02:52] Function: __upload_one_file_act
<E> [14:02:52] Website parameters: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:02:52] Waiting 20 seconds before retrying...
<E> [14:03:12] Request Try #3 / 5
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/hdd
<D> Params: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:03:12] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [14:03:12] Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Traceback (most recent call last):
  File "/home/goldcome/bin/bypy", line 1027, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

<E> [14:03:12] Function: __upload_one_file_act
<E> [14:03:12] Website parameters: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:03:12] Waiting 30 seconds before retrying...
<E> [14:03:42] Request Try #4 / 5
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/hdd
<D> Params: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:03:42] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [14:03:42] Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Traceback (most recent call last):
  File "/home/goldcome/bin/bypy", line 1027, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

<E> [14:03:42] Function: __upload_one_file_act
<E> [14:03:42] Website parameters: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:03:42] Waiting 40 seconds before retrying...
<E> [14:04:22] Request Try #5 / 5
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/hdd
<D> Params: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:04:23] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [14:04:23] Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Traceback (most recent call last):
  File "/home/goldcome/bin/bypy", line 1027, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

<E> [14:04:23] Function: __upload_one_file_act
<E> [14:04:23] Website parameters: {u'path': u'/apps/bypy/hdd', u'ondup': u'overwrite', u'method': u'upload'}
<E> [14:04:23] Maximum number (5) of tries failed.
Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'
```

**Comment by houtianze** [comment]
有点奇怪，试试加上`--disable-ssl-check`这个参数运行？

**Comment by GoldCome** [comment]
加了 都没用 很是奇怪和郁闷，都是出现如下这个错误:
```bash
<E> [11:31:32] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [11:31:32] Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

会不会是网络的问题，我在家里的服务器Exsi上新建个全新虚拟机测试也是不成功，都是授权成功，也能查看文件，但就是不能上传和下载文件。但在公司的服务器上新建个虚拟机测试确没有问题。

**Comment by houtianze** [comment]
看来可能是之前我改的urllib3 SSL的问题，晚上我看看。

**Comment by houtianze** [comment]
检查了一下，应该是上次没改对。。。你再下载一下最新版，加`--disable-ssl-check`参数运行应该可以了。

**Comment by GoldCome** [comment]
用`git pull`升级了，但还是传不了，同样的错误：
```bash
[goldcome@CentOS temp]$ bypy upload hello-world -v -d --disable-ssl-check
Token file: '/home/goldcome/.bypy.json'
Hash Cache file: '/home/goldcome/.bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
Verbose level = 1
Debug = 1
----

Loading Hash Cache File '/home/goldcome/.bypy.pickle'...
Hash Cache File not found, no caching
<D> Token loaded:
<D> {u'access_token': u'21.86553718883b583fa2ee8a7662c86032.2592000.1426075674.2298967843-1572671', u'expires_in': 2592000, u'session_secret': u'06f2528f5e3621faa574658399630352', u'scope': u'basic netdisk', u'session_key': u'9mnRfCQhykVBryK3ENu2+56ziECj9JWztIv4Ot6GMY0oGZo1iBADj69Vedp/FhOXwQKRvOGTre+q9Hb3joucT1K95AJrtWCvlQ==', u'refresh_token': u'22.6493aadf4066767f41563658fea25141.315360000.1738843674.2298967843-1572671'}
<D> Uploading file 'hello-world'
<D> __get_file_info(): rdir : /apps/bypy | rfile: hello-world
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/hello-world
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> HTTP Status Code: 200
<D> Request OK, processing action
<D> List json: {u'list': [{u'isdir': 1, u'ctime': 1423191933, u'fs_id': 265285115969819, u'mtime': 1423191933, u'path': u'/apps/bypy/app', u'md5': u'', u'size': 0}, {u'isdir': 1, u'ctime': 1423187559, u'fs_id': 834630456105269, u'mtime': 1423187559, u'path': u'/apps/bypy/gitlab', u'md5': u'', u'size': 0}, {u'isdir': 1, u'ctime': 1423173452, u'fs_id': 551999220372715, u'mtime': 1423173452, u'path': u'/apps/bypy/home', u'md5': u'', u'size': 0}], u'request_id': 2603085784}
<D> remote path is '/apps/bypy/hello-world'
<D> 'hello-world' is small and being non-slicing uploaded.
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/hello-world
<D> Params: {u'path': u'/apps/bypy/hello-world', u'ondup': u'overwrite', u'method': u'upload'}
<E> [20:10:46] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [20:10:46] Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Traceback (most recent call last):
  File "/home/goldcome/bin/bypy", line 1027, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

<E> [20:10:46] Function: __upload_one_file_act
<E> [20:10:46] Website parameters: {u'path': u'/apps/bypy/hello-world', u'ondup': u'overwrite', u'method': u'upload'}
<E> [20:10:46] Waiting 10 seconds before retrying...
^CSignal 2 received, Abort
Frame:
<frame object at 0x23fd920>
Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'
```

系统环境：
```
Centos7
用的是pyenv python2.9版本
```
基本上同样的环境，在公司的服务器却没问题

**Comment by houtianze** [comment]
奇怪了。你帮忙试一下，把这行：
`self.__checkssl = checkssl`
改成：
`self.__checkssl = False`
试试可以解决问题吗？

**Comment by GoldCome** [comment]
self.__checkssl = checkssl
改成：
self.__checkssl = False

这样改就可以成功上传了 
```bash
[goldcome@CentOS bypy]$ ./bypy.py upload README.md -v
Token file: '/home/goldcome/.bypy.json'
Hash Cache file: '/home/goldcome/.bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
Verbose level = 1
Debug = 0
----

Loading Hash Cache File '/home/goldcome/.bypy.pickle'...
Hash Cache File not found, no caching
/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/goldcome/.pyenv/versions/2.7.9/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
'README.md' ==> '/apps/bypy/README.md' OK.
Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'
```

**Comment by houtianze** [comment]
没道理啊。。你整个删除重新git clone一下试试？我觉得现在的逻辑应该是对的啊。。

**Comment by GoldCome** [comment]
多次测试，出现这样问题的情况是这样的。

bypy.py 这个文件程序，我是用软连接ln命令链接到 ~/bin/bypy ，如果用这个bypy这个ln后的命令时候，上传就会失败，只能直接调用原有文件路径的bypy.py命令，不能用他的软连接路径，不然就会上传和下载出错

**Comment by houtianze** [comment]
这个有点神奇，我也去试试。谢谢帮助调试。

**Comment by houtianze** [comment]
没能重现，先关了这个issue。

**Comment by GoldCome** [comment]
又测试了几次 确实应该不是ln命令 现在一切正常了 估计可能测试看误了 用最新版本 加上那个参数可以解决问题

**Comment by houtianze** [comment]
好:)
