### ISSUE TITLE
SSLERROR 后能不能不退出进程，继续重试可以么？

### ISSUE THREAD

**Issue by fy1128** [houtianze/bypy#120]
这次pull 后，即使--disable-ssl-check 也会出现分片上传一部后碰到SSL ERROR，然后就不像之前那样继续重试了，直接是自动退出进程？

我的sh 脚本中处理流程是这样子的：

inotify 检查到文件创建 - > bypy.py syncup - > bypy.py syncup （第二次） -> 检测bypy 进程结束则将文件移除。

所以，现在每次失败后，文件没有成功上传就被移除了。

```shell
Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file' [17:44:11] Exception: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed Traceback (most recent call last): File "/root/Studio/python/bypy-cnroms/bypy.py", line 1031, in __request_work params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 88, in post return request('post', url, data=data, **kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 382, in send raise SSLError(e, request=request) SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed [17:44:11] Function: __upload_slice_act [17:44:11] Website parameters: {u'type': u'tmpfile', u'method': u'upload'} [17:44:11] == SSL Error == We couldn't verify Baidu's SSL Certificate. ** Workaround *** It's most likely that the system doesn't have the corresponding CA certificate installed, and you can work-around this by re-running this program with the '--disable-ssl-check' option. But if you are really concern about security, you should add Baidu's certificate to your CA bundle (search the internet for howtos, DON'T ask me :) Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False' 
```

**Comment by houtianze** [comment]
看来又有bug了，我看看。麻烦贴个 `-d -v`的输出吗？（建议屏蔽掉那些token部分）
之前不知道有这么多的SSL error。。

**Comment by houtianze** [comment]
按理来说，`--disable-ssl-check`后requests应该不会检查certificate了，搞不懂为什么还会出现这个SSLError。。。郁闷。

**Comment by houtianze** [comment]
顺便对你的脚本提个小建议：检测bypy 进程结束，并且返回代码为零后再将文件移除。

**Comment by fy1128** [comment]
@houtianze 谢谢！这个返回代码怎么获得？怎么判断？

**Comment by houtianze** [comment]
不客气。sh的话，跑完进程立即检查`$?`变量应该就可以了。

**Comment by fy1128** [comment]
@houtianze 我能私信你吗？跑bypy.by -v -d --disable-ssl-check syncup 的输出。我输出到一个html 页面上了。

**Comment by houtianze** [comment]
好啊，你去gitter.im上发给我一下。我先私信你了，谢。
