### ISSUE TITLE
bypy raise TypeError("cafile must be None or a byte string")

### ISSUE THREAD

**Issue by petronny** [houtianze/bypy#133]
![img](http://7sbplw.com1.z0.glb.clouddn.com/screenshot-20150311_173037.png)
于是就不能授权了

**Comment by houtianze** [comment]
谢谢告知，现在应该好了。

**Comment by petronny** [comment]
虽然我这里没有改观。。。
是我个人的网络问题吗？

**Comment by petronny** [comment]
我这还是有问题。

1. `https://bypy-tianze.rhcloud.com/auth`能访问了，  
    但是手动访问`https://bypy-tianze.rhcloud.com/auth?code=........`会404
2. bypy raise TypeError("cafile must be None or a byte string")  
-d -v的结果如下
```
<E> [14:35:17] Maximum number (1) of tries failed.
I think you are WALLed, so let's authorize with the OpenShift server ...
<D> GET https://bypy-tianze.rhcloud.com/auth
<D> actargs: None
<D> Params: {u'code': '3b5fbb4ed53857fa765e956f8b587123', u'redirect_uri': u'oob'}
<E> [14:35:17] Error accessing 'https://bypy-tianze.rhcloud.com/auth'
<E> [14:35:17] Exception:
cafile must be None or a byte string
Traceback (most recent call last):
  File "/home/petron/bin/bypy", line 1226, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 282, in ssl_wrap_socket
    ctx.load_verify_locations(ca_certs, None)
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 303, in load_verify_locations
    raise TypeError("cafile must be None or a byte string")
TypeError: cafile must be None or a byte string

<E> [14:35:17] Function: __server_auth_act
<E> [14:35:17] Website parameters: {u'code': '3b5fbb4ed53857fa765e956f8b587123', u'redirect_uri': u'oob'}
<E> [14:35:17] Fatal Exception, no way to continue.
Quitting...
```

**Comment by houtianze** [comment]
有点奇怪，我刚重新授权了一下，没有问题。我的系统里没有/usr/lib/python2.7/site-packages/OpenSSL/SSL.py，可能是pyOpenSSL造成的问题？

**Comment by petronny** [comment]
果然把pyopenssl卸了就好了。
我这pyopenssl是作为goagent的依赖装的。
但是这个冲突问题如何解决呢？goagent也是要用的。。

**Comment by ibegyourpardon** [comment]
well。。最简单的方法就是再安装一个另外的python环境，然后各自调用不同的py 
环境运行。。。

**Comment by houtianze** [comment]
我再看看，看能重现不。怀疑又是字符编码问题。唉，Python2对unicode支持弱了点儿。

**Comment by houtianze** [comment]
> 经检查是装了python2-ndg-httpsclient这个包，具体原因未知。但是现在能运行了。装了pyopenssl也没关系。

额。。听起来可能是这个第三方库也是被字符编码坑了。。
