### ISSUE TITLE
上传有点大的 json 文件会失败

### ISSUE THREAD

**Issue by jouyouyun** [houtianze/bypy#152]
上传 `json` 文件([zone_info.json](https://gist.github.com/jouyouyun/341ec5780ca1af98e87b))时会失败，错误如下：
```shell
<D> Params: {u'path': u'/apps/bypy/zone_info.json', u'ondup': u'overwrite', u'method': u'upload'}
<E> [15:14:21] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [15:14:21] Exception:

Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 1258, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 977, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 849, in _raise_ssl_error
    raise WantWriteError()
WantWriteError

<E> [15:14:21] Function: __upload_one_file_act
<E> [15:14:21] Website parameters: {u'path': u'/apps/bypy/zone_info.json', u'ondup': u'overwrite', u'method': u'upload'}
<E> [15:14:21] Fatal Exception, no way to continue.
Quitting...
```

似乎不只是 `json` 文件，好像比较大的文本文件也会出错。

**Comment by houtianze** [comment]
好像和这个是一样的问题：#87
升级一下urllib3试试？

**Comment by Septembers** [comment]
论 #136 的重要性

**Comment by jouyouyun** [comment]
Thanks!

**Comment by houtianze** [comment]
@Septembers 嗯，考虑要不要把requests（包含urllib3）打包放到一起，免得各种版本的奇怪问题，不过这样做requests以后新版本的改进就享受不到了，还有就额外的磁盘空间占用，程序搬移麻烦和个人洁癖的困扰。

**Comment by Septembers** [comment]
@houtianze 由使用者决定我的建议仍然是做**环境可用性检查**
