### ISSUE TITLE
上传提示 Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file

### ISSUE THREAD

**Issue by baoyankun** [houtianze/bypy#156]
Debian 8.1

user@localhost bypy-master $ python bypy.py -dv upload ~/tmp/transfer /

上传，瞬间出现提示：
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
Verbose level = 1
Debug = 1
.......
<D> Uploading MD5 slice: 45a9da191982d66953772e48412684ce, #1 / 71
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/2015-R07-R-Onboard(0ms).tar.gz
<D> Params: {u'type': u'tmpfile', u'method': u'upload'}
<E> [14:27:03] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [14:27:03] Exception:

Traceback (most recent call last):
  File "bypy.py", line 1258, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 977, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 849, in _raise_ssl_error
    raise WantWriteError()
WantWriteError

<E> [14:27:03] Function: __upload_slice_act
<E> [14:27:03] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [14:27:03] Fatal Exception, no way to continue.
Quitting...

<E> [14:27:03] If the error is reproducible, run the program with `-dv` arguments again to get more info.

Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'

user@localhost bypy-master $

**Comment by houtianze** [comment]
好像和 #87 是同个问题，
>第一次看见这WantWriteError，搜了一下，估计是这个bug引起的？
shazow/urllib3#412
>
>试试升级urllib3到最新？

**Comment by Septembers** [comment]
@houtianze 论 #136 的重要性。。。

**Comment by houtianze** [comment]
@Septembers 嗯，这个检测/处理后面我会加强一下。

**Comment by baoyankun** [comment]
谢谢，很抱歉制造duplicate！

**Comment by houtianze** [comment]
没问题，这个错误处理上我需要改进的 ：）

**Comment by houtianze** [comment]
哦，后来看，这个应该是升级`requests`到最新版可以解决`pip install -U requests[security]`
