### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by raphaeltao** [houtianze/bypy#172]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "./bypygui.pyw", line 450, in downloadproc
    if rpath[-1] == '/':
IndexError: string index out of range

用gui，terminal提示的

**Comment by houtianze** [comment]
貌似是GUI的bug，我有空看一下。

**Comment by houtianze** [comment]
最新版应该已经修复，请`pip`安装。
