### ISSUE TITLE
AttributeError: 'ByPy' object has no attribute '_ByPy__pancookies'

### ISSUE THREAD

**Issue by fshiori** [houtianze/bypy#186]
In commit 64dc2800c74895758a22bd3011243d91a22b3ddd
```
../bypy/bypy.py syncdown -v
Loading Hash Cache File '/home/eric/.bypy/bypy.pickle'...
Hash Cache File not found, no caching
Gathering local directory ...
Done
Gathering remote directory ...
Done
Comparing ...
Done
Creating local directory 'Test'
<E> [05:03:13] Exception occurred:
Traceback (most recent call last):
  File "../bypy/bypy.py", line 3558, in main
    result = getattr(by, args.command[0])(*uargs)
  File "../bypy/bypy.py", line 3032, in syncdown
    subresult = self.__downfile(rcpath, lcpath)
  File "../bypy/bypy.py", line 2480, in __downfile
    return self.__downchunks(rfile, offset)
  File "../bypy/bypy.py", line 2399, in __downchunks
    self.__downchunks_act, (rfile, offset, rsize, start_time), headers = headers, cookies = self.__pancookies)
AttributeError: 'ByPy' object has no attribute '_ByPy__pancookies'

Abort
Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'
```

**Comment by houtianze** [comment]
Thanks for the feedback, didn't properly clean up during refactoring. Now it's fixed in the latest commit. 56cf5134534efd09a9ed4e1493455b89c9003f38
