### ISSUE TITLE
bypy upload 上传不了

### ISSUE THREAD

**Issue by crysehillmes** [houtianze/bypy#192]
上传失败，然后看 -dv 输出为：

```
Traceback (most recent call last):
  File "/home/cryse/bypy/bypy.py", line 1352, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/home/cryse/bypy/bypy.py", line 1063, in request
    return requests.request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 220, in sendall
    sent = self._send_until_done(data[total_sent:total_sent+SSL_WRITE_BLOCKSIZE])
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 206, in _send_until_done
    return self.connection.send(data)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1271, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1187, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
```

**Comment by houtianze** [comment]
感谢反馈。
查了一下，好像又是`requests / urllib3`的问题：
https://github.com/kennethreitz/requests/issues/2848

看来以后要直接放一个稳定版的`requests`进来了，这个坑有点多。。

**Comment by houtianze** [comment]
估计`requests`应该会很快（或已经）更新，试试升级一下：`pip2 install -U requests`看看能不能解决问题。

**Comment by septs** [comment]
关于"ZipApp"问题 似乎Python 2.7已经支持啦
方法大概如下：
假定"/"为python程序的root
```
/__main__.py # 这是入口
/requests    # 依赖库放平行目录
```
将这个目录压缩为zip文件 这里假定压缩后文件名为 app.zip
`python app.zip`这样就可以运行 或者
```
echo '#!/usr/bin/env python2' > app;
cat app.zip >> app; # 假设此app.zip为上面已压缩好的
chmod +x app;
```
`./app` # 这样也可以直接运行

CC @houtianze 
see http://hgoldfish.com/blogs/article/76/

**Comment by crysehillmes** [comment]
```
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages
```
requests 已经更新到最新了，还是有这个问题...

**Comment by houtianze** [comment]
@septs 非常感谢提供信息，后面看来只能做成包来发布了，程序也可以拆开模块化了。

@crysehillmes 暂时试试降级`requests`到2.7.x试试呢？据说这个bug是2.8.x才引入的。

暂时在加一些基本的健全测试，要不然现在改一点东西就如履薄冰的感觉。等这些弄好了我就看看怎么解决这个问题。

**Comment by houtianze** [comment]
最新版`bypy`强制`requests` 2.10或以上，应该已经解决这个问题。
