### ISSUE TITLE
上传到一半出现错误SysCallError: (10054, 'WSAECONNRESET')

### ISSUE THREAD

**Issue by jacwl** [houtianze/bypy#201]
<pre><code>[===========_________] 56% (*GB/*GB) ETA: *h*m (*MB/s, *h*m gone) <D> Uploading MD5 slice: 041a5178ec933f0460d848d404a1e0d9, #576 / 1024
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/1.mxf
<D> Params: {u'type': u'tmpfile', u'method': u'upload'}
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> Uploaded MD5 slice: 041a5178ec933f0460d848d404a1e0d9
'1.mxf' >>==> '/apps/bypy/1.mxf' OK.
<D> Request all goes fine
<D> Slice MD5 match, continuing next slice
[===========_________] 56% (*GB/*GB) ETA: *h*m (*MB/s, *h*m gone) <D> Uploading MD5 slice: 8dfd0ff0b4ae37b2ac5c61b6f5f07c66, #577 / 1024
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/1.mxf
<D> Params: {u'type': u'tmpfile', u'method': u'upload'}
<E> [09:37:27] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [09:37:27] Exception:
(10054, 'WSAECONNRESET')
Traceback:
Traceback (most recent call last):
  File "bypy/bypy.py", line 1405, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "bypy/bypy.py", line 1085, in request
    return requests.request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python27\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 869, in send
    self.sock.sendall(data)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 208, in sendall
    sent = self._send_until_done(data)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 198, in _send_until_done
    return self.connection.send(data)
  File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 1271, in send
    self._raise_ssl_error(self._ssl, result)
  File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 1178, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (10054, 'WSAECONNRESET')

<E> [09:37:27] Function: __upload_slice_act
<E> [09:37:27] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [09:37:27] Fatal Exception, no way to continue.
Quitting...

<E> [09:37:27] If the error is reproducible, run the program with `-dv` arguments again to get more info.

Skip saving Hash Cache since it has not been updated.</code></pre>

**Comment by houtianze** [comment]
感谢反馈。

考虑处理这个异常。另外，你试试升级一下`PyOpenSSL`到最新版试试？

**Comment by jacwl** [comment]
尝试升级了重试但发现还是会出问题

**Comment by houtianze** [comment]
好，我看看怎么改一下吧。

**Comment by jacwl** [comment]
这种情况似乎是上传时间长了才有几率出现的，我在本地测试似乎会更稳定一些，几十分钟能传完的都没有出现这种问题

但我租用的vps上出的问题就比较头疼，最近失败几率很高，传几十分钟就出错了
  
<pre><code>File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    sent = self._send_until_done(data)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 198, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1271, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1178, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')

<E> [13:06:34] Function: __upload_slice_act
<E> [13:06:34] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [13:06:34] Fatal Exception, no way to continue.
Quitting...

<E> [13:06:34] If the error is reproducible, run the program with `-dv` arguments again to get more info.

Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'</code></pre>

**Comment by houtianze** [comment]
哦，原来*nix系统也会出现这个问题啊，我尽快加行去。感谢再次反馈，圣诞快乐 :santa:
