### ISSUE TITLE
upload exception没有处理

### ISSUE THREAD

**Issue by gadget1999** [houtianze/bypy#203]
最近发现上传函数(upload_slices)里经常会有MD5的JSON为空的错误。好像是百度服务器的消息问题。这个错误没有被处理，导致整个程序退出。

能不能加个错误处理逻辑，这样的话，第100个文件失败了还能接着传其它的900个文件。

**Comment by houtianze** [comment]
感谢反馈。

能把相关的log或者你看到你的那个返回的JSON的内容贴一下吗，我试着把相关处理加进去。

**Comment by gadget1999** [comment]
多谢！下面请看在log里的信息：

[2015-12-16]  [05:25:17] : <E> Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
[2015-12-16]  [05:25:17] : <E> Exception:
No JSON object could be decoded
[2015-12-16]  [05:25:17] : <E> Function: __upload_slice_act
[2015-12-16]  [05:25:17] : <E> Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
[2015-12-16]  [05:25:17] : <E> HTTP Response Status Code: 200
[2015-12-16]  [05:25:17] : <E> Error parsing JSON Error Code from:
HTTP/1.1 
Date: Wed, 16 Dec 2015 10:24:47 GMT
Content-Type: text/json
Connection: keep-alive
x-bs-client-ip: MjQuMTg0LjE2MC45Mg==
x-bs-request-id: MTAuMTkyLjE3MS4yNTo4NjQzOjgxMTIFMM4MDI4ODI1MzM0MTg6MjAxNS0xMi0xNiAxODoyNDoyNw==
Content-Length: 0
Server: POMS/CloudUI 1.0


[2015-12-16]  [05:25:17] : <E> Exception:
Traceback (most recent call last):
  File "/home/share/bypy.py", line 1390, in __print_error_json
    dj = r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 786, in json
    return json.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

[2015-12-16]  [05:25:17] : <E> Website returned: HTTP/1.1 
Date: Wed, 16 Dec 2015 10:24:47 GMT
Content-Type: text/json
Connection: keep-alive
x-bs-client-ip: MjQuMTg0LjE2MC45Mg==
x-bs-request-id: MTAuMTkyLjE3MS4yNTo4NjQzOjgxMTIwODM4MDI4ODI1MzM0MTg6MjAxNS0xMi0xNiAxODoyNDoyNw==
Content-Length: 0
Server: POMS/CloudUI 1.0


[2015-12-16]  [05:25:17] : <E> Fatal Exception, no way to continue.
Quitting...

**Comment by houtianze** [comment]
谢谢`log`，不好意思才回复，我尽快加一下处理。圣诞快乐 :santa:

**Comment by gadget1999** [comment]
多谢! 圣诞快乐
