### ISSUE TITLE
Error JSON returned:{u'error_code': 31326, u'error_msg': u'anti hotlinking'}

### ISSUE THREAD

**Issue by gam2046** [houtianze/bypy#205]
```
Encoding for stdout / stderr: cp936
Loading Hash Cache File 'C:\Users\forDream\.bypy\bypy.pickle'...
Hash Cache File not found, no caching
<E> [17:01:08] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
Traceback:
Traceback (most recent call last):
  File "bypy.py", line 1405, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "bypy.py", line 1085, in request
    return requests.request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 608, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 664, in generate
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='lx.cdn.baidupcs.com', port=80): Read timed out.

<E> [17:01:08] Function: __downchunks_act
<E> [17:01:08] Website parameters: {u'path': u'/apps/bypy/El Capitan (nvoxel)-iso.part1.rar', u'method': u'download', u'ru': 'MC0yMDk3MTUxOQ=='}
<E> [17:01:08] Waiting 10 seconds before retrying...
<E> [17:01:18] Request Try #2 / 5
<E> [17:03:51] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
Traceback:
Traceback (most recent call last):
  File "bypy.py", line 1405, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "bypy.py", line 1085, in request
    return requests.request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 608, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 664, in generate
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='139.214.193.57', port=80): Read timed out.

<E> [17:03:51] Function: __downchunks_act
<E> [17:03:51] Website parameters: {u'path': u'/apps/bypy/El Capitan (nvoxel)-iso.part1.rar', u'method': u'download', u'ru': 'MC0yMDk3MTUxOQ=='}
<E> [17:03:51] Waiting 20 seconds before retrying...
<E> [17:04:11] Request Try #3 / 5
[____________________] 0% (20.0MB/3.5GB)  <E> [17:08:34] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
Traceback:
Traceback (most recent call last):
  File "bypy.py", line 1405, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "bypy.py", line 1085, in request
    return requests.request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 608, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 664, in generate
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='139.214.193.57', port=80): Read timed out.

<E> [17:08:34] Function: __downchunks_act
<E> [17:08:34] Website parameters: {u'path': u'/apps/bypy/El Capitan (nvoxel)-iso.part1.rar', u'method': u'download', u'ru': 'MjA5NzE1MjAtNDE5NDMwMzk='}
<E> [17:08:34] Waiting 10 seconds before retrying...
<E> [17:08:44] Request Try #2 / 5
[____________________] 3% (140.0MB/3.5GB)  <E> [17:22:50] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
Traceback:
Traceback (most recent call last):
  File "bypy.py", line 1405, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "bypy.py", line 1085, in request
    return requests.request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 608, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 664, in generate
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='139.214.193.57', port=80): Read timed out.

<E> [17:22:50] Function: __downchunks_act
<E> [17:22:50] Website parameters: {u'path': u'/apps/bypy/El Capitan (nvoxel)-iso.part1.rar', u'method': u'download', u'ru': 'MTQ2ODAwNjQwLTE2Nzc3MjE1OQ=='}
<E> [17:22:50] Waiting 10 seconds before retrying...
<E> [17:23:00] Request Try #2 / 5
<E> [17:26:29] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
Traceback:
Traceback (most recent call last):
  File "bypy.py", line 1405, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "bypy.py", line 1085, in request
    return requests.request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 608, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 734, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Python27\lib\site-packages\requests\models.py", line 664, in generate
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='139.214.193.57', port=80): Read timed out.

<E> [17:26:29] Function: __downchunks_act
<E> [17:26:29] Website parameters: {u'path': u'/apps/bypy/El Capitan (nvoxel)-iso.part1.rar', u'method': u'download', u'ru': 'MTQ2ODAwNjQwLTE2Nzc3MjE1OQ=='}
<E> [17:26:29] Waiting 20 seconds before retrying...
<E> [17:26:49] Request Try #3 / 5
<E> [17:26:54] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
Traceback:
None

<E> [17:26:54] Function: __downchunks_act
<E> [17:26:54] Website parameters: {u'path': u'/apps/bypy/El Capitan (nvoxel)-iso.part1.rar', u'method': u'download', u'ru': 'MTQ2ODAwNjQwLTE2Nzc3MjE1OQ=='}
<E> [17:26:54] HTTP Response Status Code: 403
<E> [17:26:54] Error JSON returned:{u'error_code': 31326, u'error_msg': u'anti hotlinking'}
Error code: 31326
Error Description: anti hotlinking
<E> [17:26:54] Website returned: {
    "error_code":31326,
    "error_msg":"anti hotlinking"
}

<E> [17:26:54] Waiting 30 seconds before retrying...
<E> [17:27:24] Request Try #4 / 5
```

另外建议，是否考虑在下载/上传时，采用多线程？我大致看过Baidu PCS api文档，其支持在服务端将分片的文件组合，下载到本地，组装自然也不是问题。本想自己做一个小工具，奈何百度不开放新的PCS api申请。

**Comment by houtianze** [comment]
感谢反馈。

这个貌似我重构给漏掉了。我尽快去修正。
嗯，不少人提过多线程的问题了，一直没腾下功夫来弄。刚把2 3兼容弄好，我也希望能早点加上去。

圣诞快乐 :santa:

**Comment by houtianze** [comment]
确认一下，出现这个`anti hotlinking`错误之后程序重试还能继续下载成功吗？
如果不能，把UserAgent改成`UserAgent = 'netdisk;5.2.7.2;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia'
`会解决这个问题吗？

**Comment by gam2046** [comment]
当时出现以后，程序在不断的重试，偶尔会可以下载，速度大概在100K/S的样子（12Mb带宽），但是下载没多久，会连接中断，再次出现anti hotlinking，之后再次不断尝试，运气好，又可以继续下载一小会儿。

**Comment by houtianze** [comment]
感谢信息反馈。
嗯，这个貌似百度那边的防御过重，感觉没什么好太好办法 :frowning: 。最早的相关改动在这里：
xslidian/bypy/pull/1

现在的临时处理方法也只有让程序自己重试吧。

**Comment by gam2046** [comment]
这个情况，可能是百度方面故意制造的。我现在的网络情况是，无论是采用第三方的PCS API，还是直接获得文件的下载地址，丢到下载工具里（例如FDM），亦或是直接使用百度官方的云管家（Sandboxie），没有一个速度可以超过100K/S，而通过云管家上传，可以达到满速1.5M/S。显然，这不是我的网络与百度连接困难（可上传），而且百度方面刻意限速（阴谋论），意图让我开会员（云管家不定时会让我体验会员，此时为宽带满速）。

我现在曲线救国的办法是获得下载地址以后，丢到迅雷离线下载，然后再从迅雷下载。比较无奈的是，现在网上很多资源的分享都是使用百度云，因此我这样很繁琐。

**Comment by houtianze** [comment]
嗯，这样是比较繁琐，主要是他们这个防盗链的算法是在后台，不知道具体如何运作。按理用PCS API是不应该出现这样的错误的，不过只是按理。。

把User-Agent改成百度云盘了，不知道是否有帮助。
185af2790b9e6cba8ab16f00a3a460bee8e80554

**Comment by gam2046** [comment]
我阴谋论的认为，这是官方的有意为之，让用户放弃第三方应用，转投官方应用。实事求是的说，BAT的拳头产品，一个个都不是什么好货。

从逻辑上说，PCS API是经过官方授权的操作，不应该存在盗链的可能（换而言之，针对PCS API的请求，根本就不需要检查是否盗链），因为整个请求过程都有唯一个private key保证是官方授权的应用请求，而不是第三方伪造。百度服务器认为请求有疑点，完全可以向开发者服务器发起请求，确认是否为其主动请求。

所以，我猜测有极大的概率，修改UA是无效的，百度的工程师也不会天真的看到一个UA就pass请求。修改UA是连很多初级用户都知道的手段了。就我自己碰到的情况：以前百度云的Web页面，可以通过修改URL，直接访问Wap页面，进而获得文件下载的地址。后来百度修改了，改为通过javascript判断`navigator.platform`的值，UA是否判断我不清楚，截至目前为止，百度云Web页面依旧是这么判断，为此，我还特别写了个Chrome扩展修改这个值（Chrome默认只能修改UA）。但是这个判断还是很粗糙的，只判断了`(win32|mac)`，也就是说，windows下，用个64位浏览器，啥都不用改，就能访问Wap页面。

**Comment by athrunsun** [comment]
成都电信100M。非VIP用户使用度娘盘下载越来越慢应该已经好一段时间了，我记忆当中甚至今年年初就开始了（好像更早）。百度云管家不断更新，越来越卡，下载速度越来越慢，哪怕是试用VIP遇到网络拥堵照样只有200KB左右的下载速度。不久之后抛弃Windows将工作娱乐全部转移到LinuxMint，bcloud力挽狂澜。然而不久之后下一个error一个，遂猜想度娘盘官方已强制单线程，去bcloud项目一看果不其然。既然已单线程，遂换到更轻快移植性更好的bypy，刚开始速度还挺稳定，最近也不行了，一个劲重试。度娘盘看来是用的人太多，免费2TB估计快撑不住了。OneDrive不是都因为滥用而宣称结束免费15GB空间了么。
我好像说了一大堆废话……其实我只是想表达对于这个项目作者的感谢，并且我非常赞同@gam2046 的阴谋论。
无论是*agent、shadowso*ks还是bcloud、bypy，都让我倍感python的强大。希望有一天我也能帮上你们的忙。

**Comment by houtianze** [comment]
听起来前景不是很乐观，不知道以后还有的玩儿不。。 :worried:

**Comment by houtianze** [comment]
百度问题，想不到什么太好的解决方法。
