### ISSUE TITLE
本地的文件夹带中文貌似不能同步。。。

### ISSUE THREAD

**Issue by martinsun** [houtianze/bypy#219]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "D:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "bypygui.pyw", line 440, in syncdownproc
  File "E:\workspce\PyDemo\bypy\bypy.py", line 3300, in syncdown
    same, diff, local, remote = self.__compare(rpath, localdir)
  File "E:\workspce\PyDemo\bypy\bypy.py", line 3214, in __compare
    lps = self.__local_dir_contents.allpath()
  File "E:\workspce\PyDemo\bypy\bypy.py", line 1121, in allpath
    result.append(k + '/' + p)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 3: ordinal
not in range(128)

**Comment by houtianze** [comment]
嗯？问题解决了？
