### ISSUE TITLE
运行报错：OpenShift server failed

### ISSUE THREAD

**Issue by linuxlovelz** [houtianze/bypy#220]
我的系统是ubuntu 12.04 64bit的，python版本是2.7 
第一次运行，sudo python bypy.py list

报以下错误：
Refreshing, please be patient, it may take upto 60.0 seconds...
Authorizing/refreshing with the OpenShift server ...
<E> [17:09:22] Exception:
<type 'exceptions.ValueError'> - No JSON object could be decoded
Stack:
  File "bypy.py", line 4016, in <module>
    main()
  File "bypy.py", line 3995, in main
    result = getattr(by, args.command[0])(*uargs)
  File "bypy.py", line 2144, in list
    return self.__get(pcsurl + 'file', pars, self.__list_act, (rpath, fmt))
  File "bypy.py", line 1749, in __get
    return self.__request(url, pars, act, 'GET', actargs, retry, addtoken, dumpex, **kwargs)
  File "bypy.py", line 1728, in __request
    result = self.__request_work(url, pars, act, method, actargs, addtoken, dumpex, **kwnew)
  File "bypy.py", line 1599, in __request_work
    if ENoError == self.__refresh_token(): # refresh the token and re-request
  File "bypy.py", line 1943, in __refresh_token
    result = self.__get(url, pars, self.__refresh_token_act, retry = retry, addtoken = False)
  File "bypy.py", line 1749, in __get
    return self.__request(url, pars, act, 'GET', actargs, retry, addtoken, dumpex, **kwargs)
  File "bypy.py", line 1728, in __request
    result = self.__request_work(url, pars, act, method, actargs, addtoken, dumpex, **kwnew)
  File "bypy.py", line 1582, in __request_work
    perr(formatex(ex))
  File "bypy.py", line 433, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

<E> [17:09:22] Maximum number (1) of tries failed.
OpenShift server failed, authorizing/refreshing with the Heroku server ...

然后我试了下 sudo pip install bypy，运行结果如下，好像也不能安装

Downloading/unpacking bypy
  Downloading bypy-1.2.9.tar.gz (47Kb): 47Kb downloaded
  Running setup.py egg_info for package bypy
    WARNING: Can't detect encoding for stdout / stderr, assume it's 'UTF-8'.
    Files with non-ASCII names may not be handled correctly.

    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/sh/baiduwangpan/bypy/build/bypy/setup.py", line 10, in <module>
        long_desc += pypandoc.convert('HISTORY.md', 'rst')
      File "/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py", line 50, in convert
        outputfile=outputfile, filters=filters)
      File "/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py", line 68, in _convert
        raise RuntimeError('Missing format!')
    RuntimeError: Missing format!
    Complete output from command python setup.py egg_info:
    WARNING: Can't detect encoding for stdout / stderr, assume it's 'UTF-8'.

Files with non-ASCII names may not be handled correctly.

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/sh/baiduwangpan/bypy/build/bypy/setup.py", line 10, in <module>

    long_desc += pypandoc.convert('HISTORY.md', 'rst')

  File "/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py", line 50, in convert

    outputfile=outputfile, filters=filters)

  File "/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py", line 68, in _convert

    raise RuntimeError('Missing format!')

RuntimeError: Missing format!

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /root/.pip/pip.log

**Comment by houtianze** [comment]
感谢反馈。回复的有点晚。

贴下你的`locale`输出呢？是不是没有设成`UTF-8`？

**Comment by linuxlovelz** [comment]
locale 运行结果

LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by houtianze** [comment]
哦，locale看上去没问题。

你试一下不用sudo，直接`python bypy list -dv`呢？

**Comment by jonahfang** [comment]
试试bypy.py -c然后重新授权

**Comment by linuxlovelz** [comment]
按照 jonahfang 说的重新授权就成功了，谢谢啊

**Comment by houtianze** [comment]
感谢 @jonahfang 的回答，发现原来的相关提示并不会输出，修改了一下提示，现在出现这种错误应该会输出相应的提示了。
