### ISSUE TITLE
Error accessing 'https://bypyoauth.appspot.com/auth'

### ISSUE THREAD

**Issue by tieyingli** [houtianze/bypy#251]
Recently, failed to get new token.

`
pi@sevenpi ~ $ bypy.py info -dv
Token file: '/home/pi/.bypy/bypy.json'
Hash Cache file: '/home/pi/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
Verbose level = 1
Debug = 1
----

Loading Hash Cache File '/home/pi/.bypy/bypy.pickle'...
Hash Cache File loaded.
<E> [15:57:18] Error while loading baidu pcs token:
<E> [15:57:18] Traceback (most recent call last):
  File "/usr/local/bin/bypy.py", line 1482, in __load_local_json
    with open(TokenFilePath, 'rb') as infile:
IOError: [Errno 2] No such file or directory: u'/home/pi/.bypy/bypy.json'

Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=xxxxxxpCsau1oS0MplgMKNBn
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
c87249d8650e18a811b014d014xxxxxx
<D> auth_code: c87249d8650e18a811b014d014xxxxxx
Authorizing, please be patient, it may take upto 60.0 seconds...
Authorizing with the GAE server ...
<D> GET https://bypyoauth.appspot.com/auth
<D> actargs: None
<D> Params: {u'code': 'c87249d8650e18a811b014d014xxxxxx', u'redirect_uri': u'oob'}
<E> [15:58:38] Error accessing 'https://bypyoauth.appspot.com/auth'
<E> [15:58:38] Exception:
('Connection aborted.', error(97, 'Address family not supported by protocol'))
Traceback (most recent call last):
  File "/usr/local/bin/bypy.py", line 1253, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 448, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 554, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 359, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 722, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py", line 195, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py", line 125, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/connection.py", line 87, in create_connection
    raise err
ProtocolError: ('Connection aborted.', error(97, 'Address family not supported by protocol'))

<E> [15:58:38] Function: __server_auth_act
<E> [15:58:38] Website parameters: {u'code': 'c87249d8650e18a811b014d014xxxxxx', u'redirect_uri': u'oob'}
<E> [15:58:38] Fatal Exception, no way to continue.
Quitting...

<E> [15:58:38] If the error is reproducible, run the program with `-dv` arguments again to get more info.

Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'
`

**Comment by houtianze** [comment]
感谢反馈。你这个是从这里下载的吗？看日志直接就去`appspot`了，现在代码是先去openshift和heroku去拿令牌。失败的原因应该是appspot是谷歌的，被墙了。

**Comment by tieyingli** [comment]
突然有一天好了，看来是被墙了。我改了hosts
