### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 18: ordinal not in range(128)

### ISSUE THREAD

**Issue by very99** [houtianze/bypy#283]
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
Gathering local directory ...
<E> [10:11:59] Exception occurred:
Exception:
<type 'exceptions.UnicodeDecodeError'> - 'ascii' codec can't decode byte 0xc9 in position 18: ordinal not in range(128)
Stack:
  File "/usr/local/bin/bypy.py", line 4469, in <module>
    main()
  File "/usr/local/bin/bypy.py", line 4462, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/bin/bypy.py", line 494, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/local/bin/bypy.py", line 4469, in <module>
    main()
  File "/usr/local/bin/bypy.py", line 4448, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/bin/bypy.py", line 3517, in syncdown
    same, diff, local, remote = self.__compare(rpath, localdir)
  File "/usr/local/bin/bypy.py", line 3419, in __compare
    self.__gather_local_dir(localdir)
  File "/usr/local/bin/bypy.py", line 3388, in __gather_local_dir
    for walk in self.__walk_normal_file(dir):
  File "/usr/local/bin/bypy.py", line 2062, in __walk_normal_file
    for walk in os.walk(dir, followlinks=self.__followlink):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 18: ordinal not in range(128)

**Comment by aniude** [comment]
应该是你自己环境的字符集问题.

**Comment by houtianze** [comment]
感谢反馈和回答。

- 升级最新版`pip install bypy`试试还有这个错误吗？
- 系统编码是什么设置？（`locale`的输出）

**Comment by houtianze** [comment]
Similar to #316
