### ISSUE TITLE
上传提示：ValueError: Unterminated string starting at: line 292 column 7 (char 12132)

### ISSUE THREAD

**Issue by imcc** [houtianze/bypy#318]
系统：Ubuntu 14.04.5 LTS
在Python2.7 和Python3.4下执行
```
bypy upload -v
```

报的错都是
```
Loading Hash Cache File '/home/download/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
<E> [08:26:09] Exception occurred:
Exception:
<class 'ValueError'> - Unterminated string starting at: line 292 column 7 (char 12132)
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/bypy/bypy.py", line 3226, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python3.4/dist-packages/bypy/util.py", line 70, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/bypy/bypy.py", line 3212, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/lib/python3.4/dist-packages/bypy/bypy.py", line 1516, in upload
    return self.__upload_dir(lpath, rpath, ondup)
  File "/usr/local/lib/python3.4/dist-packages/bypy/bypy.py", line 1429, in __upload_dir
    thisresult = self.__walk_upload(localpath, remotepath, ondup, walk)
  File "/usr/local/lib/python3.4/dist-packages/bypy/bypy.py", line 1413, in __walk_upload
    fileresult = self.__upload_file(lfile, rfile, ondup)
  File "/usr/local/lib/python3.4/dist-packages/bypy/bypy.py", line 1465, in __upload_file
    result = self.__upload_file_slices(localpath, remotepath, ondup)
  File "/usr/local/lib/python3.4/dist-packages/bypy/bypy.py", line 1230, in __upload_file_slices
    progress = jsonload(const.ProgressPath)
  File "/usr/local/lib/python3.4/dist-packages/bypy/util.py", line 229, in jsonload
    return json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 292 column 7 (char 12132)
```

请问怎么解决呢，谢谢。

**Comment by houtianze** [comment]
打开`~/.bypy/bypy.parts.json`看一下是否是合法的json文件？如果问题还在可以删掉这个文件再试试。

**Comment by imcc** [comment]
嗯，就是因为`~/.bypy/bypy.parts.json`不是合法的json文件造成的，我删除这个文件就好了，谢谢。
