### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by sjq597** [houtianze/bypy#342]
为什么我服务器上和本机上运行都报这个错:
```
/usr/bin/python2.7 /workspace/tools/bypy/bypy/bypy.py
Traceback (most recent call last):
  File "/workspace/tools/bypy/bypy/bypy.py", line 42, in <module>
    import json
  File "/usr/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/usr/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/workspace/tools/bypy/bypy/struct.py", line 10, in <module>
    from .util import iswindows
ValueError: Attempted relative import in non-package
```

**Comment by houtianze** [comment]
这样跑试试：
```
cd /workspace/tools/bypy
python2.7 -m bypy
```

一般的跑法是先`pip install bypy`，然后`python -m bypy`。现在已经重构成`package`，没办法只跑一个文件。
