### ISSUE TITLE
ImportError: cannot import name 'bypy'

### ISSUE THREAD

**Issue by Lavande** [houtianze/bypy#359]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/bypy/__init__.py", line 17, in <module>
    from .bypy import ByPy
  File "/usr/local/lib/python3.4/dist-packages/bypy/bypy.py", line 72, in <module>
    from . import monkey # TODO: circular import
  File "/usr/local/lib/python3.4/dist-packages/bypy/monkey.py", line 10, in <module>
    from . import bypy
ImportError: cannot import name 'bypy'
```
然后我把bypy/bypy.py的第72行注释掉了，虽然不知道为什么，但是能够正常使用了
`# from . import monkey # TODO: circular import`

**Comment by houtianze** [comment]
感谢反馈。

一不小心弄了个循环import，正在修。。

**Comment by houtianze** [comment]
升级到最新版1.5.2，这个问题应该解决了。
