### ISSUE TITLE
MultiProcess 出现 timeout value is too large.    1.56版本

### ISSUE THREAD

**Issue by bitliuxm** [houtianze/bypy#374]
尝试用 -t 指定timeout， 仍有该问题

<W> [00:28:19] Running multiple (3) processes for Direcory Upload, I don't know if things will go awry...
MainProcess: <E> [00:28:20] Exception occurred:
Exception:
<class 'OverflowError'> - timeout value is too large
Stack:
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bitliupc\AppData\Local\Programs\Python\Python36-32\Scripts\bypy.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\bypy\bypy.py", line 3613, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\bypy\util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

MainProcess: Abort
Traceback (most recent call last):
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bitliupc\AppData\Local\Programs\Python\Python36-32\Scripts\bypy.exe\__main__.py", line 9, in <module>
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\bypy\bypy.py", line 3599, in main
    result = getattr(by, args.command[0])(*uargs)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\bypy\bypy.py", line 1722, in upload
    return self.__upload_dir(lpath, rpath, ondup)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\bypy\bypy.py", line 1638, in __upload_dir
    return self.__upload_dir_multi(localpath, remotepath, ondup)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\bypy\bypy.py", line 1633, in __upload_dir_multi
    "Direcory Upload")
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\bypy\bypy.py", line 551, in __multi_process
    results = ar.get(const.TenYearInSeconds)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\multiprocess\pool.py", line 602, in get
    self.wait(timeout)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\multiprocess\pool.py", line 599, in wait
    self._event.wait(timeout)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large

**Comment by houtianze** [comment]
感谢反馈。

查了一下，Python 3的threading库有关，一个方案是换Python 2环境应该就能解决问题。
原因是Python 3 `threading.TIMEOUT_MAX`在*nix系统上都很大，不会有问题，但是在Windows下只有49天多一点，所以就抛异常了，等下我修一下。

**Comment by houtianze** [comment]
升级最新版应该能解决问题了。
