### ISSUE TITLE
报bug，Mac 下 unknown locale: UTF-8 错误

### ISSUE THREAD

**Issue by gonejack** [houtianze/bypy#383]
在Mac Sierra下报这个错误

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/Users/youi/Library/Python/2.7/lib/python/site-packages/bypy/__init__.py", line 17, in <module>
    from .bypy import ByPy
  File "/Users/youi/Library/Python/2.7/lib/python/site-packages/bypy/bypy.py", line 70, in <module>
    from . import gvar
  File "/Users/youi/Library/Python/2.7/lib/python/site-packages/bypy/gvar.py", line 15, in <module>
    SystemLanguageCode, SystemEncoding = locale.getdefaultlocale()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

因为pip install bypy提示权限不足，我改用了pip install --user bypy，安装成功后一运行python -m bypy就报这个错误，sudo python -m bypy 也是这个错误。

**Comment by houtianze** [comment]
感谢反馈。

搜了一下，应该是Mac的问题：
https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python

> If you have faced the error on MacOS X, here's the quick fix - add these lines to your ~/.bash_profile:
```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by gonejack** [comment]
Ok，确实解决了。
