### ISSUE TITLE
'tuple' object has no attribute 'split' : /bypy/util.py", line 322

### ISSUE THREAD

**Issue by ty-me** [houtianze/bypy#396]
```
E> [16:12:42] Exception occurred:
Exception:
<class 'AttributeError'> - 'tuple' object has no attribute 'split'
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 3674, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python3.6/site-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 3650, in main
    by = ByPy(**bypyopt)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 489, in __init__
    if comp_semver(const.__version__, minver) < 0:
  File "/usr/local/lib/python3.6/site-packages/bypy/util.py", line 322, in comp_semver
    v1a = v1.split('.')
AttributeError: 'tuple' object has no attribute 'split'
```

os: macos sierra
python: 3.6

**Comment by houtianze** [comment]
Thanks for the feedback. It was due to a stupid typo in the end of `const.__version__` 😓 The latest version `1.5.11` has fixed this, please update through pip. 
感谢反馈。原因 `const.__version__` 😓  最新版`1.5.11`已经修正，请用`pip`更新，谢谢。
