### ISSUE TITLE
error occurred on uploading

### ISSUE THREAD

**Issue by cnritng** [houtianze/bypy#406]
前一个文件上传没问题，到这个文件就报错了，2.7版本也出现一样的错误

, 'isdir': 0}], 'request_id': 6289583357060116663}
<D> '/test.mkv' is being RapidUploaded.
<D> [04:28:54] Cache hit for file '/test.mkv',
md5: eed58b21f3295cfe3d37a4720b6765ec
size: 1534721644
mtime: 1506564433
<D> [04:28:54] Cache miss for file '/test.mkv',
slice_md5: 8a689e536d59ed44d0c1a76b5ee2e4d7
size: 1534721644
mtime: 1506564433
<D> [04:28:54] Periodically saving Hash Cash
<D> [04:28:58] Cache miss for file '/test.mkv',
crc32: 2277549520
size: 1534721644
mtime: 1506564433
<D> [04:28:58] Periodically saving Hash Cash
<D> RapidUploading Length: 1534721644 MD5: eed58b21f3295cfe3d37a4720b6765ec, Slice-MD5: 8a689e536d59ed44d0c1a76b5ee2e4d7, CRC: 0x87c0a5d0
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: None
<D> Params: {'method': 'rapidupload', 'path': '/apps/bypy/test.mkv', 'content-length': 1534721644, 'content-md5': 'eed58b21f3295cfe3d37a4720b6765ec', 'slice-md5': '8a689e536d59ed44d0c1a76b5ee2e4d7', 'content-crc32': '0x87c0a5d0', 'ondup': 'overwrite'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?method=rapidupload&path=%2Fapps%2Fbypy%2Ftest.mkv&content-length=1534721644&content-md5=eed58b21f3295cfe3d37a4720b6765ec&slice-md5=8a689e536d59ed44d0c1a76b5ee2e4d7&content-crc32=0x87c0a5d0&ondup=overwrite&access_token=***
<D> HTTP Status Code: 404
<D> Website returned JSON: {'error_code': 31079, 'error_msg': 'file md5 not found, you should use upload api to upload the whole file.', 'request_id': 6289587529290544999}
<D> MD5 not found, rapidupload failed
<D> '/test.mkv' can't be RapidUploaded, now trying normal uploading.
<D> '/test.mkv' is being slicing uploaded.
<D> Slice size: 31457280, Pieces: 49
<E> [04:28:59] Exception occurred:
Exception:
<class 'json.decoder.JSONDecodeError'> - Unterminated string starting at: line 230 column 7 (char 8172)
Stack:
  File "/usr/bin/bypy", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 3674, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python3.6/site-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/bin/bypy", line 12, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 3657, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 1759, in upload
    return self.__upload_dir(lpath, rpath, ondup)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 1667, in __upload_dir
    result =  self.__upload_dir_single(localpath, remotepath, ondup)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 1649, in __upload_dir_single
    thisresult = self.__walk_upload(localpath, remotepath, ondup, walk)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 1634, in __walk_upload
    fileresult = self.__upload_file(lfile, rfile, ondup)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 1702, in __upload_file
    result = self.__upload_file_slices(localpath, remotepath, ondup)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 1464, in __upload_file_slices
    progress = jsonload(const.ProgressPath)
  File "/usr/local/lib/python3.6/site-packages/bypy/util.py", line 241, in jsonload
    return json.load(f)
  File "/usr/local/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 230 column 7 (char 8172)

**Comment by cnritng** [comment]
重新授权后可以正常上传了😰

**Comment by houtianze** [comment]
哦，好的，看样子是`~/.bypy/bypy.parts.json`文件被删除或损坏了。

**Comment by xxllp** [comment]
原来如此。。
