### ISSUE TITLE
bypy syncup/syncdown operation error

### ISSUE THREAD

**Issue by zinking** [houtianze/bypy#411]
root@3c2f3d2bba32:/# bypy syncup 
<E> [08:11:55] Exception occurred:
Exception:
<type 'exceptions.IOError'> - [Errno 1] Operation not permitted: './proc/kmsg'
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3674, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3657, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2872, in syncup
    compare_result = self.__compare(rpath, localdir, True)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2564, in __compare
    self.__gather_local_dir(localdir)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2534, in __gather_local_dir
    self.__proceed_local_gather(len(dir), walk)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2519, in __proceed_local_gather
    files.append((name, getfilesize(fullname), md5(fullname)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/cached.py", line 93, in __call__
    result = self.f(*args)
  File "/usr/local/lib/python2.7/dist-packages/bypy/cached.py", line 291, in md5
    with io.open(filename, 'rb') as f:
IOError: [Errno 1] Operation not permitted: './proc/kmsg'

root@3c2f3d2bba32:/# uname -a 
Linux 3c2f3d2bba32 4.9.36-x86_64-linode85 #1 SMP Thu Jul 6 15:31:23 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@3c2f3d2bba32:/# pip list
bypy (1.5.11)
certifi (2017.7.27.1)
chardet (3.0.4)
dill (0.2.7.1)
idna (2.6)
multiprocess (0.70.5)
pip (8.1.1)
requests (2.18.4)
requests-toolbelt (0.8.0)
setuptools (20.7.0)
urllib3 (1.22)
wheel (0.29.0)

**Comment by zinking** [comment]
This link seems helped http://jpetazzo.github.io/2014/08/24/syslog-docker/

**Comment by houtianze** [comment]
Thanks for the feedback.

However, you ran bypy from the root directory to upload everything on the file system? The error "Operation not permitted" is pointing to `/proc/kmsg`, a special directory that can not be read. So the program's behaviour is correct to spew the errors and bail out. You should probably run from another directory with your files to backup only.
