### ISSUE TITLE
用pip2/3在cygwin上安装后无法启动

### ISSUE THREAD

**Issue by neko-para** [houtianze/bypy#423]
提示信息如下
appengine已经安装

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests_toolbelt/_compat.py", line 49, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bypy", line 7, in <module>
    from bypy.bypy import main
  File "/usr/lib/python3.6/site-packages/bypy/__init__.py", line 17, in <module>
    from .bypy import ByPy
  File "/usr/lib/python3.6/site-packages/bypy/bypy.py", line 116, in <module>
    from requests_toolbelt import multipart
  File "/usr/lib/python3.6/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/lib/python3.6/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/lib/python3.6/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/lib/python3.6/site-packages/requests_toolbelt/_compat.py", line 51, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine'

**Comment by houtianze** [comment]
感谢反馈。

cygwin上从来没测试过（也没考虑支持），windows下的话直接用标准的原生python吧，跑应该没问题。看输出像是requests_toolbelt不支持cygwin。
