### ISSUE TITLE
在lnmp站点目录中upload/syncdown报错

### ISSUE THREAD

**Issue by wpzzz** [houtianze/bypy#428]
root@ubuntu-16-04:/home/wwwroot/default/dl# bypy syncdown  -v
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
Gathering local directory ...
<E> [01:26:34] Exception occurred:
Exception:
<type 'exceptions.UnicodeDecodeError'> - 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3674, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3657, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2748, in syncdown
    compare_result = self.__compare(rpath, localdir, False)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2564, in __compare
    self.__gather_local_dir(localdir)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2533, in __gather_local_dir
    for walk in self.__walk_normal_file(dir):
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 1092, in __walk_normal_file
    for walk in os.walk(dir, followlinks=self.__followlink):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)

本来以为是编码问题  ，但是在root目录中上传下载都没问题

**Comment by houtianze** [comment]
感谢反馈。

应该是你那个`dl`目录有些文件名乱码之类的造成系统无法正确解码成字符串，这个我以前挖了一下，貌似系统本身做不到，也就没法解决了。
