### ISSUE TITLE
使用 --move 参数出错

### ISSUE THREAD

**Issue by hanjideng** [houtianze/bypy#446]
```sh
$ bypy --move upload file.txt tmp/

<E> [13:21:49] Exception occurred:
Exception:
<class 'AttributeError'> - 'ByPy' object has no attribute 'debug'
Stack:
  File "//*****/.pyenv/versions/3.6.4/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/*****/.pyenv/versions/3.6.4/lib/python3.6/site-packages/bypy/bypy.py", line 3701, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/*****/.pyenv/versions/3.6.4/lib/python3.6/site-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/*****/.pyenv/versions/3.6.4/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/*****/.pyenv/versions/3.6.4/lib/python3.6/site-packages/bypy/bypy.py", line 3677, in main
    by = ByPy(**bypyopt)
  File "/*****/.pyenv/versions/3.6.4/lib/python3.6/site-packages/bypy/bypy.py", line 376, in __init__
    self.pd("Forcing verification since we will delete source for successful transfers.")
  File "/*****/.pyenv/versions/3.6.4/lib/python3.6/site-packages/bypy/bypy.py", line 517, in pd
    if self.debug >= level:
AttributeError: 'ByPy' object has no attribute 'debug'
```

### 看了下源码，获取self.debug的操作出现在了赋值操作之前???

**Comment by houtianze** [comment]
感谢反馈。

没错，就是因为`self.dbug`读取在赋值之前，已经修改顺序修正，更新bypy到最新版本(1.6.4)应该可以解决了。
