### ISSUE TITLE
gui界面无法打开，出错

### ISSUE THREAD

**Issue by 15256058** [houtianze/bypy#453]
` $ bypygui  
Traceback (most recent call last):
  File "/usr/bin/bypygui", line 7, in <module>
    from bypy.gui import main
  File "/usr/lib/python3.6/site-packages/bypy/gui.py", line 24, in <module>
    import tkinter as tk
  File "/usr/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
`
系统是Manjaro

**Comment by jiangzc** [comment]
sudo apt install python3-tk

**Comment by 15256058** [comment]
谢谢


在 2018年8月2日，01:24，1428571 <notifications@github.com<mailto:notifications@github.com>> 写道：


或者sudo apt install python-tk

**Comment by wzb1005** [comment]
我也遇到了同样的问题，我用的是Ubuntu16.04, 在执行bypygui后，要求授权码，粘贴后，方框消失了，没有登录进去。
