### ISSUE TITLE
bypy info认证成功后显示由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by ZM-J** [houtianze/bypy#515]
在输入token后，尝试第一次验证失败，第二次验证成功。之后，报错如下：
```
Traceback (most recent call last):
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000002C5367BC358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /houtianze/bypy/master/update/update.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002C5367BC358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无 法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\X\AppData\Local\Continuum\anaconda3\Scripts\bypy.exe\__main__.py", line 9, in <module>
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\bypy\bypy.py", line 3675, in main
    by = ByPy(**bypyopt)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\bypy\bypy.py", line 481, in __init__
    r = requests.get('https://raw.githubusercontent.com/houtianze/bypy/master/update/update.json')
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\x\appdata\local\continuum\anaconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /houtianze/bypy/master/update/update.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002C5367BC358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
```
之后做不了任何操作，包括下载上传啥的都不行
系统是win10，然后用的是anaconda prompt

**Comment by houtianze** [comment]
谢谢反馈。
raw github被墙了。。。 #514 
已修正，重新安装最新版(`1.6.7`)应该就没这个问题了。
