### ISSUE TITLE
python3 setup.py install 

### ISSUE THREAD

**Issue by chenli118** [houtianze/bypy#516]
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

**Comment by chenli118** [comment]
Loading mirror speeds from cached hostfile
Package libffi-3.0.13-18.el7.x86_64 already installed and latest version
Package libffi-devel-3.0.13-18.el7.x86_64 already installed and latest version
Nothing to do

**Comment by chenli118** [comment]
Collecting bypy
  Downloading http://mirrors.aliyun.com/pypi/packages/a3/a1/3ff36ddab7c3b458d25b4a90dc9ed8eee71e183a9f2c0e151d2c25f0852c/bypy-1.6.7-py2.py3-none-any.whl (237 kB)
     |████████████████████████████████| 237 kB 42.0 MB/s
Requirement already satisfied: requests-toolbelt>=0.8.0 in /usr/local/lib/python3.8/site-packages (from bypy) (0.9.1)
Collecting multiprocess>=0.70.0
  Downloading http://mirrors.aliyun.com/pypi/packages/58/17/5151b6ac2ac9b6276d46c33369ff814b0901872b2a0871771252f02e9192/multiprocess-0.70.9.tar.gz (1.6 MB)
     |████████████████████████████████| 1.6 MB 47.6 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-13c6d6e4/multiprocess/setup.py'"'"'; __file__='"'"'/tmp/pip-install-13c6d6e4/multiprocess/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-13c6d6e4/multiprocess/pip-egg-info
         cwd: /tmp/pip-install-13c6d6e4/multiprocess/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by chenli118** [comment]
源码 和pip3 都装不上。

**Comment by chenli118** [comment]
已解决 装完 libffi-devel 后再编译一下python3.8 就可以了。
[solved] : build python3.8 before install libffi-devel ,rebuild python3.8 .make clean make & make install
