### ISSUE TITLE
上传 zip 文件失败

### ISSUE THREAD

**Issue by zhuliwen** [houtianze/bypy#527]
```Loading Hash Cache File '/home/zlw/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
<E> [10:53:02] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [10:53:02] Function: __rapidupload_file_act
<E> [10:53:02] Website parameters: {'content-md5': '0b1488374e2bd0eee01a2bec540a9fbd', 'content-crc32': '0x7bae2451', 'ondup': 'overwrite', 'method': 'rapidupload', 'path': '/apps/bypy/chains
.zip', 'content-length': 42406721142, 'slice-md5': '4799545ac99bc85d43920add1c0d8c18'}
<E> [10:53:02] Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=121.951618ac6125ba2e4ff39bcbc292a2d9.Y3kd3riYxgaeeUoPzzBfs4qsa7W0oKGv0bfj2OD.AhsMmQ&content-md5=0b1488374e2bd0eee
01a2bec540a9fbd&content-crc32=0x7bae2451&ondup=overwrite&method=rapidupload&path=%2Fapps%2Fbypy%2Fchains.zip&content-length=42406721142&slice-md5=4799545ac99bc85d43920add1c0d8c18
<E> [10:53:02] HTTP Response Status Code: 400
<E> [10:53:02] Error JSON returned:{'error_code': 31023, 'error_msg': 'param error', 'request_id': 2886428004767347295}
Error code: 31023
Error Description: param error
<E> [10:53:02] Website returned: {"error_code":31023,"error_msg":"param error","request_id":2886428004767347295}
<E> [10:53:02] Waiting 10 seconds before retrying...
```

```
Traceback (most recent call last):
  File "/home/zlw/.local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/home/zlw/.local/lib/python3.5/site-packages/bypy/bypy.py", line 3687, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/home/zlw/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1777, in upload
    return self.__upload_file(lpath, rpath, ondup)
  File "/home/zlw/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1724, in __upload_file
    result = self.__upload_file_slices(localpath, remotepath, ondup)
  File "/home/zlw/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1486, in __upload_file_slices
    progress = jsonload(const.ProgressPath)
  File "/home/zlw/.local/lib/python3.5/site-packages/bypy/util.py", line 241, in jsonload
    return json.load(f)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Skip saving Hash Cache since it has not been updated.
```

**Comment by Jadyn928** [comment]
请问第一个问题得到解决了吗？我遇到了同样的问题。

**Comment by qlindazm** [comment]
同样的问题，无法上传一个30G的.gz文件
