### ISSUE TITLE
bypy 1.7.0 cannot install -U

### ISSUE THREAD

**Issue by coronin** [houtianze/bypy#577]
pip install bypy -U bypy

报错如下

KeyError: "There is no item named 'bypy/test/testdir/\\xe6\\xb1\\x89\\xe5\\xad\\x97.txt' in the archive"

是python2.7

**Comment by houtianze** [comment]
谢谢反馈。

能贴个完整些的log吗？
我看一下啥问题，貌似把测试脚本打包进去了？

**Comment by coronin** [comment]
> ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 404, in run
    pycompile=options.compile,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/req_install.py", line 824, in install
    requested=self.user_supplied,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/install/wheel.py", line 845, in install_wheel
    requested=requested,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/install/wheel.py", line 674, in _install_wheel
    file.save()
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/install/wheel.py", line 437, in save
    zipinfo = self._getinfo()
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/operations/install/wheel.py", line 416, in _getinfo
    return self._zip_file.getinfo(self.src_record_path.encode("utf-8"))
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'bypy/test/testdir/\\xe6\\xb1\\x89\\xe5\\xad\\x97.txt' in the archive"

**Comment by houtianze** [comment]
已复现（Python 2才有这个问题）并修复。

请安装最先版(`1.7.2`)应该没有问题了。
