### ISSUE TITLE
[1.7.10] 无法认证，报配置错误

### ISSUE THREAD

**Issue by Vimos** [houtianze/bypy#602]
```
(base) vimos@vimosmu ➜  ~ bypy -dv
usage: bypy [-h] [-V] [-d] [-v] [-r RETRY] [-q] [-t TIMEOUT] [-s SLICE]
            [--chunk CHUNK] [-e] [-f] [--no-resume-download]
            [--include-regex INCREGEX] [--on-dup ONDUP] [--no-symlink]
            [--disable-ssl-check] [--cacerts CACERTS] [--mirror MIRROR]
            [--select-fastest-mirror] [--rapid-upload-only]
            [--resume-download-revert-back RCOUNT] [--move]
            [--processes PROCESSES] [--downloader DOWNLOADER]
            [--downloader-arguments DOWNLOADER_ARGS] [--config-dir CONFIGDIR]
            [-c]
            [command [command ...]]

bypy v1.7.10 - Python client for Baidu Yun (Personal Cloud Storage) 百度云/百度网盘 Python 客户端
```

```
(base) vimos@vimosmu ➜  ~ bypy list
<E> [13:11:15] Fail to load '/home/vimos/.bypy/bypy.json' as json, exception:
Exception:
<class 'FileNotFoundError'> - [Errno 2] No such file or directory: '/home/vimos/.bypy/bypy.json'
Stack:
  File "/home/vimos/anaconda3/bin/bypy", line 8, in <module>
    sys.exit(main())
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/bypy/bypy.py", line 3793, in main
    by = ByPy(**bypyopt)
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/bypy/bypy.py", line 466, in __init__
    if not self.__load_local_json():
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/bypy/bypy.py", line 935, in __load_local_json
    self.__json = jsonload(self.__tokenpath)
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/bypy/util.py", line 256, in jsonload
    perr("Fail to load '{}' as json, exception:\n{}".format(filename, formatex(ex)))
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Traceback (most recent call last):
  File "/home/vimos/anaconda3/bin/bypy", line 8, in <module>
    sys.exit(main())
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/bypy/bypy.py", line 3793, in main
    by = ByPy(**bypyopt)
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/bypy/bypy.py", line 466, in __init__
    if not self.__load_local_json():
  File "/home/vimos/anaconda3/lib/python3.6/site-packages/bypy/bypy.py", line 936, in __load_local_json
    self.__access_token = self.__json['access_token']
KeyError: 'access_token'
```

**Comment by houtianze** [comment]
感谢反馈。上一个commit改了一个bug，但又增加了其他的bug。已修复。
请更新到最新版应该就可以了。

**Comment by Vimos** [comment]
新版本`1.7.12`能够正常使用。
