### ISSUE TITLE
其他功能都正常，无法同步或对比

### ISSUE THREAD

**Issue by zm1990s** [houtianze/bypy#62]
大致终端信息是：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/flow/ruanjian/bypy-master/bypygui.pyw", line 465, in compareproc
    self.byp.compare(rpath, lpath)
  File "/home/flow/ruanjian/bypy-master/bypy.py", line 2341, in compare
    same, diff, local, remote = self.__compare(get_pcs_path(remotedir), localdir)
  File "/home/flow/ruanjian/bypy-master/bypy.py", line 2287, in __compare
    self.__gather_local_dir(localdir)
  File "/home/flow/ruanjian/bypy-master/bypy.py", line 2257, in __gather_local_dir
    os.path.walk(dir, self.__proceed_local_gather, len(dir))
  File "/usr/lib/python2.7/posixpath.py", line 246, in walk
    walk(name, func, arg)
  File "/usr/lib/python2.7/posixpath.py", line 246, in walk
    walk(name, func, arg)
  File "/usr/lib/python2.7/posixpath.py", line 246, in walk
    walk(name, func, arg)
  File "/usr/lib/python2.7/posixpath.py", line 246, in walk
    walk(name, func, arg)
  File "/usr/lib/python2.7/posixpath.py", line 238, in walk
    func(arg, top, names)
  File "/home/flow/ruanjian/bypy-master/bypy.py", line 2236, in __proceed_local_gather
    fullname = os.path.join(dirname, name)
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 5: ordinal not in range(128)

请问这是什么问题？我同步的是文件夹，里面很多很多资料，大部分是Linux下创建的，部分从别人那直接拷的（存在ext3上）

**Comment by houtianze** [comment]
搜了一圈，最后结论是这个问题在Python 2.x下没有完美解决方案。。。原因是Python 2.x的os.walk()无法完美支持unicode。。。（Python 3的已经早就通过pep383修正，但是。。。这个修正不能back port到Python 2.x，参见这里：http://bugs.python.org/issue22862 ）

既然程序解决不了，只能用改名大法了。

关于技术上的细节，可参见一下讨论：
http://stackoverflow.com/questions/21772271/unicodedecodeerror-when-performing-os-walk
http://stackoverflow.com/questions/16918063/unicodedecodeerror-during-encode
http://www.python.org/dev/peps/pep-0383/
http://bugs.python.org/issue22862
https://wiki.python.org/moin/UnicodeDecodeError

**Comment by houtianze** [comment]
又看了一下这个问题和Python os.walk()和unicode的一些文档，我觉得出错原因可能是缺省的`localpath = ''`而不是'`ocalpath = `**u**`''`造成——如果直接给os.walk()一个unicode的字符串进去，我猜应该没这个问题了。
最新改动： d8ac49766b26d16004d1c2d9056a9468547e49cf
