### ISSUE TITLE
bypy info 绑定失败  

### ISSUE THREAD

**Issue by Wanggggggggggggggg** [houtianze/bypy#691]

**Comment by Wanggggggggggggggg** [comment]
之前还可以下 下了900多个g 一直retry 重新绑定 bypy info 输入授权码后就出现这个错误

**Comment by Wanggggggggggggggg** [comment]
急急急

**Comment by Wanggggggggggggggg** [comment]
<D> Auth servers loaded: {'AuthServerList': [['https://bypyoa.vercel.app/api/auth', False, 'Authorizing with the Vercel server ...'], ['https://qcfpba.api.cloudendpoint.cn/auth', False, 'Vercel server failed, Authorizing with the cloudendpoint server ...'], ['https://8.142.131.121:8443/auth', False, 'Vercel server failed. Last resort: authorizing with the Aliyun server ...']], 'RefreshServerList': [['https://bypyoa.vercel.app/api/refresh', False, 'Refreshing with the Vercel server ...'], ['https://qcfpba.api.cloudendpoint.cn/refresh', False, 'Vercel server failed, Refreshing with the cloudendpoint server ...'], ['https://8.142.131.121:8443/refresh', False, 'Vercel server failed. Last resort: refreshing with the Aliyun server ...']]}
<D> [14:44:07] Using requests.packages.urllib3 to disable warnings
<D> [14:44:07] Using urllib3 to disable warnings
Loading Hash Cache File '/home/whn2023/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
----
Verbose level = 1
Debug level = 1
Config directory: '/home/whn2023/.bypy'
Token file: '/home/whn2023/.bypy/bypy.json'
Hash Cache file: '/home/whn2023/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {'access_token': '121.3acdcf0a3fedf191c2b2cb9ce491bbed.YlRUgSajaqQZrol4h8c7-JNlLtel7EcaOYh9xRe.8B45mw', 'expires_in': 2592000, 'refresh_token': '122.a31e30023273a74e6c6721e769985c27.YQrZR5dxIaIvVUQSXCI_U_bDCWdDsOihCdQWGvL.ENVwMQ', 'scope': 'basic netdisk', 'session_key': '', 'session_secret': ''}
<D> GET https://pcs.baidu.com/rest/2.0/pcs/quota
<D> actargs: None
<D> Params: {'method': 'info'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/quota?method=info&access_token=121.3acdcf0a3fedf191c2b2cb9ce491bbed.YlRUgSajaqQZrol4h8c7-JNlLtel7EcaOYh9xRe.8B45mw
<D> HTTP Status Code: 200
<D> 200 OK, processing action
Traceback (most recent call last):
  File "/data/whn2023/.conda/envs/Pointnet++/bin/bypy", line 8, in <module>
    sys.exit(main())
  File "/data/whn2023/.conda/envs/Pointnet++/lib/python3.7/site-packages/bypy/bypy.py", line 3853, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/data/whn2023/.conda/envs/Pointnet++/lib/python3.7/site-packages/bypy/bypy.py", line 1233, in info
    return self.quota()
  File "/data/whn2023/.conda/envs/Pointnet++/lib/python3.7/site-packages/bypy/bypy.py", line 1239, in quota
    return self._get(pcsurl + 'quota', pars, self._quota_act)
  File "/data/whn2023/.conda/envs/Pointnet++/lib/python3.7/site-packages/bypy/bypy.py", line 905, in _get
    return self._request(url, pars, act, 'GET', actargs, retry, addtoken, dumpex, **kwargs)
  File "/data/whn2023/.conda/envs/Pointnet++/lib/python3.7/site-packages/bypy/bypy.py", line 883, in _request
    result = self._request_work(url, pars, act, method, actargs, addtoken, dumpex, **kwnew)
  File "/data/whn2023/.conda/envs/Pointnet++/lib/python3.7/site-packages/bypy/bypy.py", line 725, in _request_work
    result = act(r, actargs)
  File "/data/whn2023/.conda/envs/Pointnet++/lib/python3.7/site-packages/bypy/bypy.py", line 1194, in _quota_act
    pr('Quota: ' + human_size(j['quota']))
KeyError: 'quota'
Skip saving Hash Cache since it has not been updated.

**Comment by Wanggggggggggggggg** [comment]
-
