### ISSUE TITLE
syncup错误

### ISSUE THREAD

**Issue by Zeroman** [houtianze/bypy#87]
10几天没有使用bypy，这几天使用发现syncdown, list, upload都没有问题，唯独syncup会出现如下问题：
<E> [12:18:24] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
Traceback (most recent call last):
  File "/work/src/git/bypy/bypy.py", line 1005, in __request_work
    params = parsnew, timeout = self.__timeout, verify = False, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 327, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, *_httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 203, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 977, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 849, in _raise_ssl_error
    raise WantWriteError()
WantWriteError

<E> [12:18:24] Function: __upload_slice_act
<E> [12:18:24] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [12:18:24] Fatal Exception.
Quitting...
总是同步上传不了。
我的系统是
uname -a
Linux Zeroman 3.16-2-amd64 #1 SMP Debian 3.16.3-2 (2014-09-20) x86_64 GNU/Linux

**Comment by houtianze** [comment]
升级requests到最新版应该可以解决：
`pip install -U requests[security]`
